### ISSUE TITLE
getting told that there is an unexpected close tag but no error message is being displayed when i try and retrieve any file

### ISSUE THREAD

**Issue by arch563** [chrishasz/spgo#124]
When I try and retrieve files i get an error saying that there is an unexpected close tag on line nine column 7, i do not have a line 9 in my SPGo.Json
here is the error message:

[13/08/2020, 15:03:48] Unexpected close tag
Line: 9
Column: 7
Char: >
[13/08/2020, 15:03:48] Error Detail:
[13/08/2020, 15:03:48] ----------------------
[13/08/2020, 15:03:48] {}
[13/08/2020, 15:03:48] ===========================================================================

and my SPGo.json file

{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://bakerhughes.sharepoint.com/sites/DTCTOinterns",
    "publishingScope": "SaveOnly",
    "authenticationType": "Digest"
}

not sure what is happening here so any help would be appreciated!

**Comment by chrishasz** [comment]
Hello @arch563, sorry for the late reply. Can you confirm for me which folder you are trying to sync? I've seen this issue before when trying to synchronize publishing/page folders (e.g. `/sitepages`) via API.

**Comment by ArakP** [comment]
I also facing this issue as well, with the same exact configuration as @arch563

**Comment by ArakP** [comment]
assume it's authentication issue, my SharePoint online is using one-login with OIDC (OpenID Connect) method for authentication.

**Comment by chrishasz** [comment]
Hello @ArakP - unfortunately SPGo's authenticaion will not work if you are using a third-party interactive identity provider.

**Comment by ArakP** [comment]
Hi @chrishasz thanks for confirmation. I wonder, even the third-party using OAuth2.0 standard for authentication. There should be a way to take it and follow the authentication flow just like ADFS.

**Comment by chrishasz** [comment]
@ArakP the trouble here is that most 3rd party IDPs require interactive login which is a common scheme for OAuth flows. Interactive login means that you need to enter your username + password into a webpage and, unfortunately, VSCode and the authentication libraries that I use under the covers do not support opening a web browser to perform the

As a workaround, you could try one of these approaches:
- [Addin-only Authentication](https://www.chrishasz.com/spgo/authentication/addin-only-authentication)
- [App Password Authentication](https://www.chrishasz.com/spgo/authentication/app-password-authentication)

Let me know if either of these work for you.

**More Context:**
I have had another user report a similar issue, and provided the source of the error that you see. It originates from the `node-sp-auth` library and appears to occur when attempting to use ADFS/external authentication to request the login token.

```
=== Error ===
 TypeError: Cannot read property 'firstChild' of undefined
    at /Users/******/node-sp-auth-troubleshoot/node_modules/node-sp-auth/lib/src/utils/AdfsHelper.js:29:69
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/*****/node-sp-auth-troubleshoot/index.js:22:24
```

**Comment by ArakP** [comment]
@chrishasz thanks I'll check this out, don't think I could figure this out soon though.
